function ET2022hclusters = importClustersNew(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ET2022HCLUSTERS = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  ET2022HCLUSTERS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  ET2022hclusters = importfile("C:\Users\usuario\Documents\MATLAB\microsismica\ET2022h clusters.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Aug-2023 13:10:26

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
ET2022hclusters = readtable(filename, opts);

%% Convert to output type
ET2022hclusters = table2array(ET2022hclusters);
end