function ET = importSurveyReport2021(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  ET = IMPORTFILE(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the data as a
%  table.
%
%  ET = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  ET = IMPORTFILE(FILE, SHEET, DATALINES) reads from the specified
%  worksheet for the specified row interval(s). Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  ET = importfile("G:\Mi unidad\Proyecto Fracking\Microsismica\ET.xp-2021 Pilot_Survey_Run10_8.5in_3330.07m.xlsx", "Sheet1", [24, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-May-2023 15:29:42

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [24, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 12);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["Comments", "MDm", "Incl", "AzimGrid", "TVDm", "VSECm", "NSm", "EWm", "Closurem", "ClosureAzimuth", "DLS30m", "BR30m"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "string", "string", "double", "double", "double", "string"];

% Specify variable properties
opts = setvaropts(opts, ["Comments", "NSm", "EWm", "BR30m"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Comments", "NSm", "EWm", "BR30m"], "EmptyFieldRule", "auto");

% Import the data
ET = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    ET = [ET; tb]; %#ok<AGROW>
end

for i = 1:length(ET.EWm)
    str = convertStringsToChars(ET.EWm(i));
    numero = str2double(str(3:end));  % Convierte el número a tipo double

    if contains(str,'E')
        ET.EWm(i) = numero * 1;  
    elseif contains(str,'W')
        ET.EWm(i) = numero * -1;  % Multiplica el número por -1
    else
    end

end
ET.EWm = str2double(ET.EWm);

for i = 1:length(ET.NSm)
    str = convertStringsToChars(ET.NSm(i));
    numero = str2double(str(3:end));  % Convierte el número a tipo double

    if contains(str,'N')
        ET.NSm(i) = numero * 1;  
    elseif contains(str,'S')
        ET.NSm(i) = numero * -1;  % Multiplica el número por -1
    else
    end

end
ET.NSm = str2double(ET.NSm);

end