function ET2022hSurveyReportRun078 = importSurveyReport(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  ET2022HSURVEYREPORTRUN078 = IMPORTFILE(FILE) reads data from the
%  first worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  ET2022HSURVEYREPORTRUN078 = IMPORTFILE(FILE, SHEET) reads from the
%  specified worksheet.
%
%  ET2022HSURVEYREPORTRUN078 = IMPORTFILE(FILE, SHEET, DATALINES) reads
%  from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  ET2022hSurveyReportRun078 = importfile("G:\Mi unidad\Proyecto Fracking\Microsismica\ET-2022(h)_Survey_Report_Run07_8.5in @4549.77m TD.xlsx", "Sheet1", [24, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 23-Mar-2023 10:03:05

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [24, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 13);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["Comments", "MDm", "Incl", "AzimGrid", "TVDm", "VSECm", "NSm", "EWm", "Closurem", "ClosureAzimuth", "DLS30m", "BR30m", "TF"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];

% Specify variable properties
opts = setvaropts(opts, ["Comments", "TF"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Comments", "TF"], "EmptyFieldRule", "auto");

% Import the data
ET2022hSurveyReportRun078 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    ET2022hSurveyReportRun078 = [ET2022hSurveyReportRun078; tb]; %#ok<AGROW>
end

end