function Clusters = importClusters(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CLUSTERS = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  CLUSTERS = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Clusters = importfile("G:\Mi unidad\Proyecto Fracking\Microsismica\Clusters.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 28-Mar-2023 16:06:38

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName1", "TrimNonNumeric", true);
opts = setvaropts(opts, "VarName1", "ThousandsSeparator", ",");

% Import the data
Clusters = readtable(filename, opts);

%% Convert to output type
Clusters = table2array(Clusters);

for i = 0:14
    aux(i+1,:) = Clusters(i*10+1:((i+1)*10));
end
Clusters = aux;
end